ame: Deploy to AWS EC2
description: send to AWS
runs: runs

on:
  push:
    branches:
	- main
jobs: 
	build-deploy:
		run-on: ubuntu-latest

		steps:
   		  - name: Checkout
      		uses: actions/checkout@v3

		  - name: Login to Docker Hub
      		uses: docker/login-act@v1
			with: 
				username: ${{secrets.DOCKER_USERNAME}}
				password: ${{secrets.DOCKER_PASSWORD}}
		  - name: Build and push Docker image
		    uses: docker/build-push-action@v2
			with:  
				context: .
				push: true
				tags: docker/${{github.repository}}:${{github.run.attemp}}

	     - name: Deploy to EC2 instance
		   uses: appleboy/ssh-action@master
		   with: 
				host:
				username:
				key: 
				script: |
      				export DC_IMAGE_NAME=docker/${{github.repository}}
      				export DC_IMAGE_TAG=${{github.run.attemp}}
      				export DOMEN_NAME=${{secrets.STAGE_DOMEN_NAME}}
      				docker-compose -f docker-compose.nginx.yml up -d
			